#!/bin/bash

CURDIR=$PWD

#cd build && make && cd src && g++ -fopenmp CMakeFiles/Oscillator.dir/Oscillator.cpp.o -o Oscillator   -L/cvmfs/larsoft.opensciencegrid.org/products/root/v6_18_02a/Linux64bit+3.10-2.17-e17-prof/lib  -Wl,-rpath, -L/cvmfs/larsoft.opensciencegrid.org/products/root/v6_18_02a/Linux64bit+3.10-2.17-e17-prof/lib:/dune/app/users/pgranger/MaCh3_ana/MaCh3_DUNE/build/samplePDFDUNE:/dune/app/users/pgranger/MaCh3_ana/MaCh3_DUNE/build/splines:/dune/app/users/pgranger/MaCh3_ana/MaCh3_DUNE/build/_deps/mach3-build/mcmc:/dune/app/users/pgranger/MaCh3_ana/MaCh3_DUNE/build/_deps/mach3-build/samplePDF:/dune/app/users/pgranger/MaCh3_ana/MaCh3_DUNE/build/_deps/mach3-build/OscClass:/dune/app/users/pgranger/MaCh3_ana/MaCh3_DUNE/build/_deps/mach3-build/covariance:/dune/app/users/pgranger/MaCh3_ana/MaCh3_DUNE/build/_deps/mach3-build/splines:/dune/app/users/pgranger/MaCh3_ana/MaCh3_DUNE/build/_deps/mach3-build/throwParms:/dune/app/users/pgranger/MaCh3_ana/MaCh3_DUNE/build/_deps/mach3-build/manager:/dune/app/users/pgranger/MaCh3_ana/MaCh3_DUNE/build/_deps/yaml-cpp-build: ../samplePDFDUNE/libSamplePDFDUNE.so ../splines/libsplinesDUNE.so ../_deps/mach3-build/mcmc/libMCMC.so  /dune/app/users/pgranger/MaCh3_ana/MaCh3_DUNE/build/_deps/mach3-build/OscClass/libOscClass.so ../_deps/mach3-build/covariance/libCovariance.so ../_deps/mach3-build/splines/libSplines.so ../_deps/mach3-build/throwParms/libThrowParms.so -lCore -lRIO -lXMLIO -lNet -lHist -lGraf -lGraf3d -lGpad -lTree -lRint -lPostscript -lMatrix -lPhysics -lMathMore -lMathCore -lThread -lEG -lGeom -lGenVector ../_deps/mach3-build/manager/libManager.so ../_deps/yaml-cpp-build/libyaml-cpp.so.0.7.0 ../_deps/mach3-build/samplePDF/libSamplePDF.so


cd build
make install
cd src

/cvmfs/dune.opensciencegrid.org/products/dune/gcc/v7_3_0/Linux64bit+3.10-2.17/bin/g++ -g -fopenmp CMakeFiles/Oscillator.dir/Oscillator.cpp.o -o Oscillator   -L/cvmfs/larsoft.opensciencegrid.org/products/root/v6_18_02a/Linux64bit+3.10-2.17-e17-prof/lib  -Wl,-rpath,/cvmfs/larsoft.opensciencegrid.org/products/root/v6_18_02a/Linux64bit+3.10-2.17-e17-prof/lib:/dune/app/users/pgranger/MaCh3_ana/MaCh3_DUNE/build/samplePDFDUNE:/dune/app/users/pgranger/MaCh3_ana/MaCh3_DUNE/build/splines:/dune/app/users/pgranger/MaCh3_ana/MaCh3_DUNE/build/_deps/mach3-build/mcmc:/dune/app/users/pgranger/MaCh3_ana/MaCh3_DUNE/build/_deps/mach3-build/samplePDF:/dune/app/users/pgranger/MaCh3_ana/MaCh3_DUNE/build/_deps/mach3-build/OscClass:/dune/app/users/pgranger/MaCh3_ana/MaCh3_DUNE/build/_deps/mach3-build/covariance:/dune/app/users/pgranger/MaCh3_ana/MaCh3_DUNE/build/_deps/mach3-build/splines:/dune/app/users/pgranger/MaCh3_ana/MaCh3_DUNE/build/_deps/mach3-build/throwParms:/dune/app/users/pgranger/MaCh3_ana/MaCh3_DUNE/build/_deps/mach3-build/manager:/dune/app/users/pgranger/MaCh3_ana/MaCh3_DUNE/build/_deps/yaml-cpp-build: ../samplePDFDUNE/libSamplePDFDUNE.so ../splines/libsplinesDUNE.so ../_deps/mach3-build/mcmc/libMCMC.so ../_deps/mach3-build/OscClass/libOscClass.so ../_deps/mach3-build/covariance/libCovariance.so ../_deps/mach3-build/splines/libSplines.so ../_deps/mach3-build/throwParms/libThrowParms.so -lCore -lRIO -lXMLIO -lNet -lHist -lGraf -lGraf3d -lGpad -lTree -lRint -lPostscript -lMatrix -lPhysics -lMathMore -lMathCore -lThread -lEG -lGeom -lGenVector ../_deps/mach3-build/manager/libManager.so ../_deps/yaml-cpp-build/libyaml-cppd.so.0.7.0 ../_deps/mach3-build/samplePDF/libSamplePDF.so

/cvmfs/dune.opensciencegrid.org/products/dune/gcc/v7_3_0/Linux64bit+3.10-2.17/bin/g++ -g -fopenmp CMakeFiles/DUNE_LLHscan_osc.dir/DUNE_LLHscan_osc.cpp.o -o DUNE_LLHscan_osc   -L/cvmfs/larsoft.opensciencegrid.org/products/root/v6_18_02a/Linux64bit+3.10-2.17-e17-prof/lib  -Wl,-rpath,/cvmfs/larsoft.opensciencegrid.org/products/root/v6_18_02a/Linux64bit+3.10-2.17-e17-prof/lib:/dune/app/users/pgranger/MaCh3_ana/MaCh3_DUNE/build/samplePDFDUNE:/dune/app/users/pgranger/MaCh3_ana/MaCh3_DUNE/build/splines:/dune/app/users/pgranger/MaCh3_ana/MaCh3_DUNE/build/_deps/mach3-build/mcmc:/dune/app/users/pgranger/MaCh3_ana/MaCh3_DUNE/build/_deps/mach3-build/samplePDF:/dune/app/users/pgranger/MaCh3_ana/MaCh3_DUNE/build/_deps/mach3-build/OscClass:/dune/app/users/pgranger/MaCh3_ana/MaCh3_DUNE/build/_deps/mach3-build/covariance:/dune/app/users/pgranger/MaCh3_ana/MaCh3_DUNE/build/_deps/mach3-build/splines:/dune/app/users/pgranger/MaCh3_ana/MaCh3_DUNE/build/_deps/mach3-build/throwParms:/dune/app/users/pgranger/MaCh3_ana/MaCh3_DUNE/build/_deps/mach3-build/manager:/dune/app/users/pgranger/MaCh3_ana/MaCh3_DUNE/build/_deps/yaml-cpp-build: ../samplePDFDUNE/libSamplePDFDUNE.so ../splines/libsplinesDUNE.so ../_deps/mach3-build/mcmc/libMCMC.so ../_deps/mach3-build/OscClass/libOscClass.so ../_deps/mach3-build/covariance/libCovariance.so ../_deps/mach3-build/splines/libSplines.so ../_deps/mach3-build/throwParms/libThrowParms.so -lCore -lRIO -lXMLIO -lNet -lHist -lGraf -lGraf3d -lGpad -lTree -lRint -lPostscript -lMatrix -lPhysics -lMathMore -lMathCore -lThread -lEG -lGeom -lGenVector ../_deps/mach3-build/manager/libManager.so ../_deps/yaml-cpp-build/libyaml-cppd.so.0.7.0 ../_deps/mach3-build/samplePDF/libSamplePDF.so


/cvmfs/dune.opensciencegrid.org/products/dune/gcc/v7_3_0/Linux64bit+3.10-2.17/bin/g++ -g -fopenmp CMakeFiles/DUNE_LLHscan_systs.dir/DUNE_LLHscan_systs.cpp.o -o DUNE_LLHscan_systs   -L/cvmfs/larsoft.opensciencegrid.org/products/root/v6_18_02a/Linux64bit+3.10-2.17-e17-prof/lib  -Wl,-rpath,/cvmfs/larsoft.opensciencegrid.org/products/root/v6_18_02a/Linux64bit+3.10-2.17-e17-prof/lib:/dune/app/users/pgranger/MaCh3_ana/MaCh3_DUNE/build/samplePDFDUNE:/dune/app/users/pgranger/MaCh3_ana/MaCh3_DUNE/build/splines:/dune/app/users/pgranger/MaCh3_ana/MaCh3_DUNE/build/_deps/mach3-build/mcmc:/dune/app/users/pgranger/MaCh3_ana/MaCh3_DUNE/build/_deps/mach3-build/samplePDF:/dune/app/users/pgranger/MaCh3_ana/MaCh3_DUNE/build/_deps/mach3-build/OscClass:/dune/app/users/pgranger/MaCh3_ana/MaCh3_DUNE/build/_deps/mach3-build/covariance:/dune/app/users/pgranger/MaCh3_ana/MaCh3_DUNE/build/_deps/mach3-build/splines:/dune/app/users/pgranger/MaCh3_ana/MaCh3_DUNE/build/_deps/mach3-build/throwParms:/dune/app/users/pgranger/MaCh3_ana/MaCh3_DUNE/build/_deps/mach3-build/manager:/dune/app/users/pgranger/MaCh3_ana/MaCh3_DUNE/build/_deps/yaml-cpp-build: ../samplePDFDUNE/libSamplePDFDUNE.so ../splines/libsplinesDUNE.so ../_deps/mach3-build/mcmc/libMCMC.so ../_deps/mach3-build/OscClass/libOscClass.so ../_deps/mach3-build/covariance/libCovariance.so ../_deps/mach3-build/splines/libSplines.so ../_deps/mach3-build/throwParms/libThrowParms.so -lCore -lRIO -lXMLIO -lNet -lHist -lGraf -lGraf3d -lGpad -lTree -lRint -lPostscript -lMatrix -lPhysics -lMathMore -lMathCore -lThread -lEG -lGeom -lGenVector ../_deps/mach3-build/manager/libManager.so ../_deps/yaml-cpp-build/libyaml-cppd.so.0.7.0 ../_deps/mach3-build/samplePDF/libSamplePDF.so
/cvmfs/dune.opensciencegrid.org/products/dune/gcc/v7_3_0/Linux64bit+3.10-2.17/bin/g++ -g -fopenmp CMakeFiles/DUNE_atm_chain.dir/DUNE_atm_chain.cpp.o -o DUNE_atm_chain   -L/cvmfs/larsoft.opensciencegrid.org/products/root/v6_18_02a/Linux64bit+3.10-2.17-e17-prof/lib  -Wl,-rpath,/cvmfs/larsoft.opensciencegrid.org/products/root/v6_18_02a/Linux64bit+3.10-2.17-e17-prof/lib:/dune/app/users/pgranger/MaCh3_ana/MaCh3_DUNE/build/samplePDFDUNE:/dune/app/users/pgranger/MaCh3_ana/MaCh3_DUNE/build/splines:/dune/app/users/pgranger/MaCh3_ana/MaCh3_DUNE/build/_deps/mach3-build/mcmc:/dune/app/users/pgranger/MaCh3_ana/MaCh3_DUNE/build/_deps/mach3-build/samplePDF:/dune/app/users/pgranger/MaCh3_ana/MaCh3_DUNE/build/_deps/mach3-build/OscClass:/dune/app/users/pgranger/MaCh3_ana/MaCh3_DUNE/build/_deps/mach3-build/covariance:/dune/app/users/pgranger/MaCh3_ana/MaCh3_DUNE/build/_deps/mach3-build/splines:/dune/app/users/pgranger/MaCh3_ana/MaCh3_DUNE/build/_deps/mach3-build/throwParms:/dune/app/users/pgranger/MaCh3_ana/MaCh3_DUNE/build/_deps/mach3-build/manager:/dune/app/users/pgranger/MaCh3_ana/MaCh3_DUNE/build/_deps/yaml-cpp-build: ../samplePDFDUNE/libSamplePDFDUNE.so ../splines/libsplinesDUNE.so ../_deps/mach3-build/mcmc/libMCMC.so ../_deps/mach3-build/OscClass/libOscClass.so ../_deps/mach3-build/covariance/libCovariance.so ../_deps/mach3-build/splines/libSplines.so ../_deps/mach3-build/throwParms/libThrowParms.so -lCore -lRIO -lXMLIO -lNet -lHist -lGraf -lGraf3d -lGpad -lTree -lRint -lPostscript -lMatrix -lPhysics -lMathMore -lMathCore -lThread -lEG -lGeom -lGenVector ../_deps/mach3-build/manager/libManager.so ../_deps/yaml-cpp-build/libyaml-cppd.so.0.7.0 ../_deps/mach3-build/samplePDF/libSamplePDF.so

cd $CURDIR
