SampleName: "nueselec"
SampleType: "Atm"
MaCh3ModeConfig: "configs/CovObjs/MaCh3Modes.yaml"
DetID: "ATM"

Binning:
  XVarStr: "RecoCosineZ"
  XVarBins: [-1, -0.8, -0.6, -0.4, -0.2, 0, 0.2, 0.4, 0.6, 0.8, 1]
  YVarStr: "RecoNeutrinoEnergy"
  YVarBins: [0, 0.11, 0.19, 0.33, 0.62, 1.34, 3.35, 16.28, 1e8]

SampleBools:
  IsELike: yes

InputFiles:
  mtupleprefix: "inputs/Atmospherics/CAFs/atm_hd"
  mtuplesuffix: "_nueselec.root"
  splineprefix: ""
  splinesuffix: ""

NuOsc:
  NuOscConfigFile: "configs/NuOsc/CUDAProb3.yaml"
  EqualBinningPerOscChannel: true

SubSamples:
  - Name: "nue_x_nue"
    LatexName: "nue_x_nue"
    mtuplefile: "nue_x_nue"
    splinefile: "nue_x_nue"
    nutype: 12
    oscnutype: 12
  - Name: "nue_x_numu"
    LatexName: "nue_x_numu"
    mtuplefile: "nue_x_numu"
    splinefile: "nue_x_numu"
    nutype: 12
    oscnutype: 14
  - Name: "nue_x_nutau"
    LatexName: "nue_x_nutau"
    mtuplefile: "nue_x_nutau"
    splinefile: "nue_x_nutau"
    nutype: 12
    oscnutype: 16
  - Name: "numu_x_nue"
    LatexName: "numu_x_nue"
    mtuplefile: "numu_x_nue"
    splinefile: "numu_x_nue"
    nutype: 14
    oscnutype: 12
  - Name: "numu_x_numu"
    LatexName: "numu_x_numu"
    mtuplefile: "numu_x_numu"
    splinefile: "numu_x_numu"
    nutype: 14
    oscnutype: 14
  - Name: "numu_x_nutau"
    LatexName: "numu_x_nutau"
    mtuplefile: "numu_x_nutau"
    splinefile: "numu_x_nutau"
    nutype: 14
    oscnutype: 16
  - Name: "nuebar_x_nuebar"
    LatexName: "nuebar_x_nuebar"
    mtuplefile: "nuebar_x_nuebar"
    splinefile: "nuebar_x_nuebar"
    nutype: -12
    oscnutype: -12
  - Name: "nuebar_x_numubar"
    LatexName: "nuebar_x_numubar"
    mtuplefile: "nuebar_x_numubar"
    splinefile: "nuebar_x_numubar"
    nutype: -12
    oscnutype: -14
  - Name: "nuebar_x_nutaubar"
    LatexName: "nuebar_x_nutaubar"
    mtuplefile: "nuebar_x_nutaubar"
    splinefile: "nuebar_x_nutaubar"
    nutype: -12
    oscnutype: -16