Systematics:


#V2 initial commit
#WARNING !!!
#osc covariance require particular order of osc parameters, do not change order of dials here
- Systematic:
    Names:
      FancyName: sin2th_12
      ParameterName: sin2th_12


    DetID: 984
    Error: 0.0129961532770277840
    FlatPrior: false
    ParameterBounds: [0, 1]
    ParameterGroup: Osc
    ParameterValues:
      Generated: 0.303
      PreFitValue: 0.303
    StepScale:
      MCMC: 1.0
    Type: Osc


- Systematic:
    Names:
      FancyName: sin2th_23
      ParameterName: sin2th_23


    DetID: 984
    Error: 0.021
    FlatPrior: true
    ParameterBounds: [0, 1]
    ParameterGroup: Osc
    ParameterValues:
      Generated: 0.451
      PreFitValue: 0.451
    StepScale:
      MCMC: 1.0
    Type: Osc


- Systematic:
    Names:
      FancyName: sin2th_13
      ParameterName: sin2th_13


    DetID: 984
    Error: 0.0007
    FlatPrior: true
    ParameterBounds: [0, 1]
    ParameterGroup: Osc
    ParameterValues:
      Generated: 0.02225
      PreFitValue: 0.02225
    StepScale:
      MCMC: 5.0
    Type: Osc


- Systematic:
    Names:
      FancyName: delm2_12
      ParameterName: delm2_12


    DetID: 984
    Error: 0.0000018
    FlatPrior: false
    ParameterBounds: [-999, 999]
    ParameterGroup: Osc
    ParameterValues:
      Generated: 0.0000741
      PreFitValue: 0.0000741
    StepScale:
      MCMC: 1.0
    Type: Osc


- Systematic:
    Names:
      FancyName: delm2_23
      ParameterName: delm2_23


    DetID: 984
    Error: 0.000034
    FlatPrior: true
    ParameterBounds: [-999, 999]
    ParameterGroup: Osc
    ParameterValues:
      Generated: 0.0024599
      PreFitValue: 0.0024599
    StepScale:
      MCMC: 1.0
    Type: Osc


- Systematic:
    Names:
      FancyName: delta_cp
      ParameterName: delta_cp


    DetID: 984
    Error: 6.28331122896200340
    FlatPrior: true
    # It has special treatment as it is continuous param
    ParameterBounds: [-999, 999]
    ParameterGroup: Osc
    ParameterValues:
      Generated: -1.601
      PreFitValue: -1.601
    StepScale:
      MCMC: 1.0
    Type: Osc

### sterile stuff ###
# - Systematic:
#     Names:
#       FancyName: sin2th_14
#       ParameterName: sin2th_14


#     DetID: 984
#     Error: 0.0001
#     FlatPrior: true
#     # It has special treatment as it is continuous param
#     ParameterBounds: [-999, 999]
#     ParameterGroup: Osc
#     ParameterValues:
#       Generated: 0.01
#       PreFitValue: 0.01
#     StepScale:
#       MCMC: 1.0
#     Type: Osc

# - Systematic:
#     Names:
#       FancyName: sin2th_24
#       ParameterName: sin2th_24


#     DetID: 984
#     Error: 0.0001
#     FlatPrior: true
#     # It has special treatment as it is continuous param
#     ParameterBounds: [-999, 999]
#     ParameterGroup: Osc
#     ParameterValues:
#       Generated: 0.03
#       PreFitValue: 0.03
#     StepScale:
#       MCMC: 1.0
#     Type: Osc

# - Systematic:
#     Names:
#       FancyName: sin2th_34
#       ParameterName: sin2th_34


#     DetID: 984
#     Error: 0.0001
#     FlatPrior: true
#     # It has special treatment as it is continuous param
#     ParameterBounds: [-999, 999]
#     ParameterGroup: Osc
#     ParameterValues:
#       Generated: 0.05
#       PreFitValue: 0.05
#     StepScale:
#       MCMC: 1.0
#     Type: Osc

# - Systematic:
#     Names:
#       FancyName: delm2_14
#       ParameterName: delm2_14


#     DetID: 984
#     Error: 0.0001
#     FlatPrior: true
#     # It has special treatment as it is continuous param
#     ParameterBounds: [-999, 999]
#     ParameterGroup: Osc
#     ParameterValues:
#       Generated: 0.1
#       PreFitValue: 0.1
#     StepScale:
#       MCMC: 1.0
#     Type: Osc

# - Systematic:
#     Names:
#       FancyName: delta_14
#       ParameterName: delta_14


#     DetID: 984
#     Error: 0.0001
#     FlatPrior: true
#     # It has special treatment as it is continuous param
#     ParameterBounds: [-999, 999]
#     ParameterGroup: Osc
#     ParameterValues:
#       Generated: 0.
#       PreFitValue: 0.
#     StepScale:
#       MCMC: 1.0
#     Type: Osc

# - Systematic:
#     Names:
#       FancyName: delta_24
#       ParameterName: delta_24


#     DetID: 984
#     Error: 0.0001
#     FlatPrior: true
#     # It has special treatment as it is continuous param
#     ParameterBounds: [-999, 999]
#     ParameterGroup: Osc
#     ParameterValues:
#       Generated: 0.
#       PreFitValue: 0.
#     StepScale:
#       MCMC: 1.0
#     Type: Osc

### NSI stuff ###
- Systematic:
   Names:
     FancyName: Eps_ee
     ParameterName: Eps_ee


   DetID: 984
   Error: 0.001
   FlatPrior: true
   # It has special treatment as it is continuous param
   ParameterBounds: [-999, 999]
   ParameterGroup: Osc
   ParameterValues:
     Generated: -0.5
     PreFitValue: -0.5
   StepScale:
     MCMC: 1.0
   Type: Osc

- Systematic:
   Names:
     FancyName: Eps_emu
     ParameterName: Eps_emu


   DetID: 984
   Error: 0.001
   FlatPrior: true
   # It has special treatment as it is continuous param
   ParameterBounds: [-999, 999]
   ParameterGroup: Osc
   ParameterValues:
     Generated: 0.02
     PreFitValue: 0.02
   StepScale:
     MCMC: 1.0
   Type: Osc

- Systematic:
   Names:
     FancyName: Eps_etau
     ParameterName: Eps_etau


   DetID: 984
   Error: 0.001
   FlatPrior: true
   # It has special treatment as it is continuous param
   ParameterBounds: [-999, 999]
   ParameterGroup: Osc
   ParameterValues:
     Generated: 0.1
     PreFitValue: 0.1
   StepScale:
     MCMC: 1.0
   Type: Osc

- Systematic:
   Names:
     FancyName: Eps_mumu
     ParameterName: Eps_mumu


   DetID: 984
   Error: 0.001
   FlatPrior: true
   # It has special treatment as it is continuous param
   ParameterBounds: [-999, 999]
   ParameterGroup: Osc
   ParameterValues:
     Generated: 0.03
     PreFitValue: 0.03
   StepScale:
     MCMC: 1.0
   Type: Osc

- Systematic:
   Names:
     FancyName: Eps_mutau
     ParameterName: Eps_mutau


   DetID: 984
   Error: 0.001
   FlatPrior: true
   # It has special treatment as it is continuous param
   ParameterBounds: [-999, 999]
   ParameterGroup: Osc
   ParameterValues:
     Generated: 0.05
     PreFitValue: 0.05
   StepScale:
     MCMC: 1.0
   Type: Osc

- Systematic:
   Names:
     FancyName: Eps_tautau
     ParameterName: Eps_tautau


   DetID: 984
   Error: 0.001
   FlatPrior: true
   # It has special treatment as it is continuous param
   ParameterBounds: [-999, 999]
   ParameterGroup: Osc
   ParameterValues:
     Generated: 0.25
     PreFitValue: 0.25
   StepScale:
     MCMC: 1.0
   Type: Osc

- Systematic:
   Names:
     FancyName: Delta_emu
     ParameterName: Delta_emu


   DetID: 984
   Error: 0.001
   FlatPrior: true
   # It has special treatment as it is continuous param
   ParameterBounds: [-999, 999]
   ParameterGroup: Osc
   ParameterValues:
     Generated: 0.
     PreFitValue: 0.
   StepScale:
     MCMC: 1.0
   Type: Osc

- Systematic:
   Names:
     FancyName: Delta_etau
     ParameterName: Delta_etau


   DetID: 984
   Error: 0.001
   FlatPrior: true
   # It has special treatment as it is continuous param
   ParameterBounds: [-999, 999]
   ParameterGroup: Osc
   ParameterValues:
     Generated: 0.
     PreFitValue: 0.
   StepScale:
     MCMC: 1.0
   Type: Osc

- Systematic:
   Names:
     FancyName: Delta_mutau
     ParameterName: Delta_mutau


   DetID: 984
   Error: 0.001
   FlatPrior: true
   # It has special treatment as it is continuous param
   ParameterBounds: [-999, 999]
   ParameterGroup: Osc
   ParameterValues:
     Generated: 0.
     PreFitValue: 0.
   StepScale:
     MCMC: 1.0
   Type: Osc

- Systematic:
   Names:
     FancyName: ElecCoup
     ParameterName: ElecCoup


   DetID: 984
   Error: 0.001
   FlatPrior: true
   # It has special treatment as it is continuous param
   ParameterBounds: [-999, 999]
   ParameterGroup: Osc
   ParameterValues:
     Generated: 0.02
     PreFitValue: 0.02
   StepScale:
     MCMC: 1.0
   Type: Osc

- Systematic:
   Names:
     FancyName: UpCoup
     ParameterName: UpCoup


   DetID: 984
   Error: 0.001
   FlatPrior: true
   # It has special treatment as it is continuous param
   ParameterBounds: [-999, 999]
   ParameterGroup: Osc
   ParameterValues:
     Generated: 0.04
     PreFitValue: 0.04
   StepScale:
     MCMC: 1.0
   Type: Osc

- Systematic:
   Names:
     FancyName: DownCoup
     ParameterName: DownCoup


   DetID: 984
   Error: 0.001
   FlatPrior: true
   # It has special treatment as it is continuous param
   ParameterBounds: [-999, 999]
   ParameterGroup: Osc
   ParameterValues:
     Generated: 0.04
     PreFitValue: 0.04
   StepScale:
     MCMC: 1.0
   Type: Osc