#!/bin/bash
OUTFOLDER=comparedmach3contours_270717
OUTNAMEBASE="comparedmach3contours"
mkdir $OUTFOLDER
OUTNAME="$OUTFOLDER/$OUTNAMEBASE"

MACH3WORCMCFOLDER="contours_woRC_asimovA_270717"
MACH3WRCMCFOLDER="contours_wRC_asimovA_270717"

MACH3WORCDATAFOLDER="contours_woRC_datafit_270717"
MACH3WRCDATAFOLDER="contours_wRC_datafit_270717"

MACH3WORC1TO7DATAFOLDER="TN300contours/data/woRC/"
MACH3WRC1TO7DATAFOLDER="TN300contours/data/wRC/"



FILEBASE="contours_th23dm23_both.root"
NHFILEBASE="contours_th23dm23_NH.root"
IHFILEBASE="contours_th23dm23_IH.root"

APPFILEBASE="contours_th13dcp_both.root"
APPNHFILEBASE="contours_th13dcp_NH.root"
APPIHFILEBASE="contours_th13dcp_IH.root"

DCPFILEBASE="contours_app1D_both.root"
DCPNHFILEBASE="contours_app1D_NH.root"
DCPIHFILEBASE="contours_app1D_IH.root"

#!!add 1D to all of this
MACH3MCNHWORCFILE="$MACH3WORCMCFOLDER/$NHFILEBASE"
MACH3MCIHWORCFILE="$MACH3WORCMCFOLDER/$IHFILEBASE"
MACH3MCNHWORCAPPFILE="$MACH3WORCMCFOLDER/$APPNHFILEBASE"
MACH3MCIHWORCAPPFILE="$MACH3WORCMCFOLDER/$APPIHFILEBASE"
MACH3MCNHWORCDCPFILE="$MACH3WORCMCFOLDER/$DCPNHFILEBASE"
MACH3MCIHWORCDCPFILE="$MACH3WORCMCFOLDER/$DCPIHFILEBASE"

MACH3MCNHWRCFILE="$MACH3WRCMCFOLDER/$NHFILEBASE"
MACH3MCIHWRCFILE="$MACH3WRCMCFOLDER/$IHFILEBASE"
MACH3MCNHWRCAPPFILE="$MACH3WRCMCFOLDER/$APPNHFILEBASE"
MACH3MCIHWRCAPPFILE="$MACH3WRCMCFOLDER/$APPIHFILEBASE"
MACH3MCNHWRCDCPFILE="$MACH3WRCMCFOLDER/$DCPNHFILEBASE"
MACH3MCIHWRCDCPFILE="$MACH3WRCMCFOLDER/$DCPIHFILEBASE"

MACH3DATANHWORCFILE="$MACH3WORCDATAFOLDER/$NHFILEBASE"
MACH3DATAIHWORCFILE="$MACH3WORCDATAFOLDER/$IHFILEBASE"
MACH3DATANHWORCAPPFILE="$MACH3WORCDATAFOLDER/$APPNHFILEBASE"
MACH3DATAIHWORCAPPFILE="$MACH3WORCDATAFOLDER/$APPIHFILEBASE"
MACH3DATANHWORCDCPFILE="$MACH3WORCDATAFOLDER/$DCPNHFILEBASE"
MACH3DATAIHWORCDCPFILE="$MACH3WORCDATAFOLDER/$DCPIHFILEBASE"

MACH3DATANHWRCFILE="$MACH3WRCDATAFOLDER/$NHFILEBASE"
MACH3DATAIHWRCFILE="$MACH3WRCDATAFOLDER/$IHFILEBASE"
MACH3DATANHWRCAPPFILE="$MACH3WRCDATAFOLDER/$APPNHFILEBASE"
MACH3DATAIHWRCAPPFILE="$MACH3WRCDATAFOLDER/$APPIHFILEBASE"
MACH3DATANHWRCDCPFILE="$MACH3WRCDATAFOLDER/$DCPNHFILEBASE"
MACH3DATAIHWRCDCPFILE="$MACH3WRCDATAFOLDER/$DCPIHFILEBASE"

MACH31TO7DATANHWORCFILE="$MACH3WORC1TO7DATAFOLDER/2d_disapp_plots/jointFitNue1pi_data_woRC_sth23dm32_nh.root"
MACH31TO7DATAIHWORCFILE="$MACH3WORC1TO7DATAFOLDER/2d_disapp_plots/jointFitNue1pi_data_woRC_sth23dm32_ih.root"
MACH31TO7DATANHWORCAPPFILE="$MACH3WORC1TO7DATAFOLDER/2d_app_plots/jointFitNue1pi_data_woRC_sth13dcp_nh.root"
MACH31TO7DATAIHWORCAPPFILE="$MACH3WORC1TO7DATAFOLDER/2d_app_plots/jointFitNue1pi_data_woRC_sth13dcp_ih.root"
MACH31TO7DATANHWORCDCPFILE="$MACH3WORC1TO7DATAFOLDER/1d_plots/jointFitNue1pi_data_woRC_1d_nh.root"
MACH31TO7DATAIHWORCDCPFILE="$MACH3WORC1TO7DATAFOLDER/1d_plots/jointFitNue1pi_data_woRC_1d_ih.root"

MACH31TO7DATANHWRCFILE="$MACH3WRC1TO7DATAFOLDER/2d_disapp_plots/jointFitNue1pi_data_wRC_sth23dm32_nh.root"
MACH31TO7DATAIHWRCFILE="$MACH3WRC1TO7DATAFOLDER/2d_disapp_plots/jointFitNue1pi_data_wRC_sth23dm32_ih.root"
MACH31TO7DATANHWRCAPPFILE="$MACH3WRC1TO7DATAFOLDER/2d_app_plots/jointFitNue1pi_data_wRC_sth13dcp_nh.root"
MACH31TO7DATAIHWRCAPPFILE="$MACH3WRC1TO7DATAFOLDER/2d_app_plots/jointFitNue1pi_data_wRC_sth13dcp_ih.root"
MACH31TO7DATANHWRCDCPFILE="$MACH3WRC1TO7DATAFOLDER/1d_plots/jointFitNue1pi_data_wRC_1d_nh.root"
MACH31TO7DATAIHWRCDCPFILE="$MACH3WRC1TO7DATAFOLDER/1d_plots/jointFitNue1pi_data_wRC_1d_ih.root"

#wRC vs woRC asimov
root -l -q 'utils/CompareContours.C("'$MACH3MCNHWORCFILE'","'$MACH3MCNHWRCFILE'","woRC","wRC",false,"'$OUTNAME'_RCeff_asimovA_NH",true)'
root -l -q 'utils/CompareContours.C("'$MACH3MCIHWORCFILE'","'$MACH3MCIHWRCFILE'","woRC","wRC",false,"'$OUTNAME'_RCeff_asimovA_IH",false)'
root -l -q 'utils/CompareContours.C("'$MACH3MCNHWORCAPPFILE'","'$MACH3MCNHWRCAPPFILE'","woRC","wRC",true,"'$OUTNAME'_RCeff_app_asimovA_NH")'
root -l -q 'utils/CompareContours.C("'$MACH3MCIHWORCAPPFILE'","'$MACH3MCIHWRCAPPFILE'","woRC","wRC",true,"'$OUTNAME'_RCeff_app_asimovA_IH")'
root -l -q 'utils/CompareContours1Ddcp.C("'$MACH3MCNHWORCDCPFILE'","'$MACH3MCNHWRCDCPFILE'","woRC","wRC","'$OUTNAME'_RCeff_dcp_asimovA_NH")'
root -l -q 'utils/CompareContours1Ddcp.C("'$MACH3MCIHWORCDCPFILE'","'$MACH3MCIHWRCDCPFILE'","woRC","wRC","'$OUTNAME'_RCeff_dcp_asimovA_IH")'

#wRC vs woRC data
root -l -q 'utils/CompareContours.C("'$MACH3DATANHWORCFILE'","'$MACH3DATANHWRCFILE'","woRC","wRC",false,"'$OUTNAME'_RCeff_data_NH",true)'
root -l -q 'utils/CompareContours.C("'$MACH3DATAIHWORCFILE'","'$MACH3DATAIHWRCFILE'","woRC","wRC",false,"'$OUTNAME'_RCeff_data_IH",false)'

root -l -q 'utils/CompareContours.C("'$MACH3DATANHWORCAPPFILE'","'$MACH3DATANHWRCAPPFILE'","woRC","wRC",true,"'$OUTNAME'_RCeff_app_data_NH")'
root -l -q 'utils/CompareContours.C("'$MACH3DATAIHWORCAPPFILE'","'$MACH3DATAIHWRCAPPFILE'","woRC","wRC",true,"'$OUTNAME'_RCeff_app_data_IH")'
root -l -q 'utils/CompareContours1Ddcp.C("'$MACH3DATANHWORCDCPFILE'","'$MACH3DATANHWRCDCPFILE'","woRC","wRC","'$OUTNAME'_RCeff_dcp_data_NH")'
root -l -q 'utils/CompareContours1Ddcp.C("'$MACH3DATAIHWORCDCPFILE'","'$MACH3DATAIHWRCDCPFILE'","woRC","wRC","'$OUTNAME'_RCeff_dcp_data_IH")'

#asimov vs data
root -l -q 'utils/CompareContours.C("'$MACH3MCNHWORCFILE'","'$MACH3DATANHWORCFILE'","Asimov","Data",false,"'$OUTNAME'_mcdata_woRC_NH",true)'
root -l -q 'utils/CompareContours.C("'$MACH3MCIHWORCFILE'","'$MACH3DATAIHWORCFILE'","Asimov","Data",false,"'$OUTNAME'_mcdata_woRC_IH",false)'

root -l -q 'utils/CompareContours.C("'$MACH3MCNHWORCAPPFILE'","'$MACH3DATANHWORCAPPFILE'","Asimov","Data",true,"'$OUTNAME'_mcdata_app_woRC_NH")'
root -l -q 'utils/CompareContours.C("'$MACH3MCIHWORCAPPFILE'","'$MACH3DATAIHWORCAPPFILE'","Asimov","Data",true,"'$OUTNAME'_mcdata_app_woRC_IH")'
root -l -q 'utils/CompareContours1Ddcp.C("'$MACH3MCNHWORCDCPFILE'","'$MACH3DATANHWORCDCPFILE'","Asimov","Data","'$OUTNAME'_mcdata_dcp_woRC_NH")'
root -l -q 'utils/CompareContours1Ddcp.C("'$MACH3MCIHWORCDCPFILE'","'$MACH3DATAIHWORCDCPFILE'","Asimov","Data","'$OUTNAME'_mcdata_dcp_woRC_IH")'


root -l -q 'utils/CompareContours.C("'$MACH3MCNHWRCFILE'","'$MACH3DATANHWRCFILE'","Asimov","Data",false,"'$OUTNAME'_mcdata_wRC_NH",true)'
root -l -q 'utils/CompareContours.C("'$MACH3MCIHWRCFILE'","'$MACH3DATAIHWRCFILE'","Asimov","Data",false,"'$OUTNAME'_mcdata_wRC_IH",false)'

root -l -q 'utils/CompareContours.C("'$MACH3MCNHWRCAPPFILE'","'$MACH3DATANHWRCAPPFILE'","Asimov","Data",true,"'$OUTNAME'_mcdata_app_wRC_NH",true)'
root -l -q 'utils/CompareContours.C("'$MACH3MCIHWRCAPPFILE'","'$MACH3DATAIHWRCAPPFILE'","Asimov","Data",true,"'$OUTNAME'_mcdata_app_wRC_IH",true)'
root -l -q 'utils/CompareContours1Ddcp.C("'$MACH3MCNHWRCDCPFILE'","'$MACH3DATANHWRCDCPFILE'","Asimov","Data","'$OUTNAME'_mcdata_dcp_wRC_NH")'
root -l -q 'utils/CompareContours1Ddcp.C("'$MACH3MCIHWRCDCPFILE'","'$MACH3DATAIHWRCDCPFILE'","Asimov","Data","'$OUTNAME'_mcdata_dcp_wRC_IH")'

#1-7 vs 1-8 data
root -l -q 'utils/CompareContours.C("'$MACH31TO7DATANHWORCFILE'","'$MACH3DATANHWORCFILE'","Run 1-7","Run 1-8",false,"'$OUTNAME'_2016vs17_woRC_NH",true)'
root -l -q 'utils/CompareContours.C("'$MACH31TO7DATAIHWORCFILE'","'$MACH3DATAIHWORCFILE'","Run 1-7","Run 1-8",false,"'$OUTNAME'_2016vs17_woRC_IH",false)'
root -l -q 'utils/CompareContours.C("'$MACH31TO7DATANHWORCAPPFILE'","'$MACH3DATANHWORCAPPFILE'","Run 1-7","Run 1-8",true,"'$OUTNAME'_2016vs17_app_woRC_NH")'
root -l -q 'utils/CompareContours.C("'$MACH31TO7DATAIHWORCAPPFILE'","'$MACH3DATAIHWORCAPPFILE'","Run 1-7","Run 1-8",true,"'$OUTNAME'_2016vs17_app_woRC_IH")'
root -l -q 'utils/CompareContours1Ddcp.C("'$MACH31TO7DATANHWORCDCPFILE'","'$MACH3DATANHWORCDCPFILE'","Run 1-7","Run 1-8","'$OUTNAME'_2016vs17_dcp_woRC_NH")'
root -l -q 'utils/CompareContours1Ddcp.C("'$MACH31TO7DATAIHWORCDCPFILE'","'$MACH3DATAIHWORCDCPFILE'","Run 1-7","Run 1-8","'$OUTNAME'_2016vs17_dcp_woRC_IH")'

root -l -q 'utils/CompareContours.C("'$MACH31TO7DATANHWRCFILE'","'$MACH3DATANHWRCFILE'","Run 1-7","Run 1-8",false,"'$OUTNAME'_2016vs17_wRC_NH",true)'
root -l -q 'utils/CompareContours.C("'$MACH31TO7DATAIHWRCFILE'","'$MACH3DATAIHWRCFILE'","Run 1-7","Run 1-8",false,"'$OUTNAME'_2016vs17_wRC_IH",false)'
root -l -q 'utils/CompareContours.C("'$MACH31TO7DATANHWRCAPPFILE'","'$MACH3DATANHWRCAPPFILE'","Run 1-7","Run 1-8",true,"'$OUTNAME'_2016vs17_app_wRC_NH",true)'
root -l -q 'utils/CompareContours.C("'$MACH31TO7DATAIHWRCAPPFILE'","'$MACH3DATAIHWRCAPPFILE'","Run 1-7","Run 1-8",true,"'$OUTNAME'_2016vs17_app_wRC_IH",true)'
root -l -q 'utils/CompareContours1Ddcp.C("'$MACH31TO7DATANHWRCDCPFILE'","'$MACH3DATANHWRCDCPFILE'","Run 1-7","Run 1-8","'$OUTNAME'_2016vs17_dcp_wRC_NH")'
root -l -q 'utils/CompareContours1Ddcp.C("'$MACH31TO7DATAIHWRCDCPFILE'","'$MACH3DATAIHWRCDCPFILE'","Run 1-7","Run 1-8","'$OUTNAME'_2016vs17_dcp_wRC_IH")'

#syst pars nd vs nd+sk
