SET(MACH3DUNE_LIB_LIST "${MACH3DUNE_LIB_LIST} -libSamplePDFDUNE")

SET(ROOT_INCLUDE_DIRS_SEP ${ROOT_INCLUDE_DIRS})
string(REPLACE ";" " -I" ROOT_INCLUDE_DIRS_SEP "-I${ROOT_INCLUDE_DIRS_SEP}")
SET(ROOT_DEFINITIONS_SEP ${ROOT_DEFINITIONS})
string(REPLACE ";" " " ROOT_DEFINITIONS_SEP "${ROOT_DEFINITIONS_SEP}")
SET(ROOT_LIBRARIES_SEP ${ROOT_LIBRARIES})
string(REPLACE ";" " " ROOT_LIBRARIES_SEP "${ROOT_LIBRARIES_SEP}")

SET(MACH3DUNE_FEATURES_LIST)

string(REPLACE ";" " " MACH3DUNE_FEATURES "${MACH3DUNE_FEATURES_LIST}")

configure_file(${CMAKE_CURRENT_LIST_DIR}/../Templates/mach3dune-config.in
  "${PROJECT_BINARY_DIR}${CMAKE_FILES_DIRECTORY}/mach3dune-config" @ONLY)
install(PROGRAMS
  "${PROJECT_BINARY_DIR}${CMAKE_FILES_DIRECTORY}/mach3dune-config" DESTINATION bin)
